config/routes.rb
Reddit::Application.routes.draw do
  resources :links do
    resources :comments, :only => [:new, :show, :create]

    member do
      get "upvote"
      get "downvote"
    end
  end
  resource :session
  resources :subs
  resources :users
end

app/models/comment.rb
module BuildExtension
  def build(params = {})
    obj = super(params)
    obj.link = proxy_association.owner.link

    obj
  end

  def create!(params = {})
    obj = build(params)
    obj.save!
  end
end

class Comment < ActiveRecord::Base
  attr_accessible :body, :parent_comment_id, :link_id

  has_many(
    :child_comments,
    :class_name => "Comment",
    :foreign_key => "parent_comment_id",

    :extend => BuildExtension
  )
  belongs_to :link
  belongs_to :parent_comment, :class_name => "Comment"

  validates :link, :presence => true
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :sub_ids, :body, :title

  has_many :comments
  belongs_to :owner, :class_name => "User"
  has_many :link_posts
  has_many :subs, :through => :link_posts
  has_many :user_votes

  before_destroy :cleanup

  validates :url, :presence => true

  def comments_by_parent
    comments_by_parent = Hash.new { |hash, key| hash[key] = [] }
    comments.each do |comment|
      comments_by_parent[comment.parent_comment_id] << comment
    end

    comments_by_parent
  end

  def votes
    votes_hash = self.user_votes.group(:direction).count
    up = votes_hash[1] || 0
    down = votes_hash[-1] || 0

    up - down
  end

  private
  def cleanup
    link_posts.each do |lp|
      # optimization to more quickly drop LinkPosts
      lp.link = nil
      lp.destroy
    end
  end
end

app/models/link_post.rb
class LinkPost < ActiveRecord::Base
  attr_accessible :sub_id, :link_id

  belongs_to :sub
  belongs_to :link

  after_destroy :cleanup

  private
  def cleanup
    return unless link_id

    # cleanup a Link when no more LinkPosts
    unless LinkPost.exists?(:link_id => link_id)
      link.destroy
    end
  end
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :name

  belongs_to :moderator, :class_name => "User"
  has_many :link_posts, :dependent => :destroy
  has_many :links, :through => :link_posts

  validates :name, :moderator, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  validates :username, :password_digest, :presence => true
  validate :password_is_long_enough

  has_many :links, :foreign_key => "owner_id"
  has_many :subs, :foreign_key => "moderator_id"
  has_many :user_votes

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def verify_password(password)
    BCrypt::Password.new(password_digest) == password
  end

  private
  def password_is_long_enough
    return if @password.nil?

    if @password.length < 6
      errors[:password] << "is not long enough"
    end
  end
end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base
  attr_accessible :user_id, :link_id, :direction

  belongs_to :user
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.build(params[:comment])

    if @comment.save
      redirect_to link_url(@link)
    else
      render :new
    end
  end

  def index
    @link = Link.find(params[:link_id])
    @comments = @link.comments
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @link = Link.find(params[:link_id])
    @comment = Comment.new
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :require_user!
  before_filter :require_owner!, :only => [:edit, :update]

  def create
    @link = current_user.links.build(params[:link])
    if @link.save
      redirect_to link_url(@link)
    else
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def show
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(params[:link])
      redirect_to link_url(@link)
    else
      render :new
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @user_vote = UserVote.find_by_link_id_and_user_id(@link.id,current_user.id)

    _vote(@user_vote,1)

    redirect_to @link
  end

  def downvote
    @link = Link.find(params[:id])
    @user_vote = UserVote.find_by_link_id_and_user_id(@link.id,current_user.id)

    _vote(@user_vote,-1)

    redirect_to @link
  end

  private

  def _vote(user_vote,direction)
    if user_vote

      user_vote.direction == direction ? user_vote.update_attributes(direction: 0) : user_vote.update_attributes(direction: direction)
    else
      UserVote.create(user_id: current_user.id, link_id: @link.id, direction: direction)
    end
  end

  def require_owner!
    @link = Link.find(params[:id])

    return if @link.nil?

    unless @link.owner == current_user
      render :text => "Unauthorized", :status => 403
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user_params = User.new(params[:user])
    @user = login_user!(@user_params)

    if @user
      redirect_to user_url(@user)
    else
      @user = @user_params
      render :new
    end
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :require_user!
  before_filter :require_moderator!, :only => [:edit, :update]

  def create
    begin
      ActiveRecord::Base.transaction do
        @sub = current_user.subs.build(name: params[:sub][:name])

        @links = params[:sub][:links_attributes].map do |_,link_params|
          Link.new(link_params)
        end

        @links.reject! { |link| link.url.empty? }

        @sub.save

        @links.each do |link|
          link.subs << @sub
          link.save
        end

        raise "invalid" unless @sub.valid? && @links.all? { |link| link.valid? }
      end

    rescue
      flash[:errors] = @sub.errors.full_messages
      redirect_to new_sub_url
    else
      redirect_to sub_url(@sub)
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    5.times { @sub.links.build }
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update_attributes(params[:sub])
      redirect_to sub_url(@sub)
    else
      render :edit
    end
  end

  private
  def correct_user!
    @sub = Sub.find(params[:id])
    redirect_to root_url unless @sub.moderator == current_user
  end

  def require_moderator!
    @sub = Sub.find(params[:id])

    return if @sub.nil?
    unless @sub.moderator == current_user
      render :text => "Unauthorized", :status => 403
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user!, :only => [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :json => @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_partial(comment, comments_by_parent)
    render(
      :partial => "comments/comment",
      :locals => {
        :comment => comment,
        :comments_by_parent => comments_by_parent
      }
    )
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login_user!(user_params)
    user = User.find_by_username(user_params.username)
    if user && user.verify_password(user_params.password)
      user.session_token = SecureRandom::urlsafe_base64(16)
      user.save!
      session[:session_token] = user.session_token

      user
    else
      nil
    end
  end

  def current_user
    return nil unless session[:session_token]
    User.find_by_session_token(session[:session_token])
  end

  def require_user!
    redirect_to new_session_url unless current_user
  end
end

app/views/comments/_comment.html.erb
<p>
  <%= link_to comment.body, link_comment_url(comment.link.id,comment.id) %>
</p>

<ul>
  <% comments_by_parent[comment.id].each do |child_comment| %>
    <li><%= comment_partial(child_comment, comments_by_parent) %></li>
  <% end %>
</ul>

app/views/comments/new.html.erb
<h1>Create Comment</h1>
<form action="<%= link_comments_url(@link) %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <textarea name="comment[body]"></textarea>

  <input type="submit">
</form>

app/views/comments/show.html.erb
<h4>"<%= @comment.body %>"</h4>
<br><br>
<form action="<%= link_comments_url(@comment.link.id) %>" method="post">
  Comment: <input type="textarea" name="comment[body]">
  <input type="hidden" name="comment[link_id]" value="<%= @comment.link_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">

  <input type="submit" value="Submit comment" class="btn">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:errors] %>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<% form_title = @link.persisted? ? "Edit Link" : "Create Link" %>
<% submit_method = @link.persisted? ? :put : :post %>
<% submit_url = @link.persisted? ? link_url(@link) : links_url %>

<h1><%= form_title %></h1>
<form action="<%= submit_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input
    type="hidden"
    name="_method"
    value="<%= submit_method %>">

  <label for="link_url">URL</label>
  <input
    type="text"
    name="link[url]"
    id="link_url"
    value="<%= @link.url %>"><br>

  <label for="link_title">Title:</label>
  <input
    type="text"
    name="link[title]"
    id="link_title"
    value="<%= @link.title %>"><br>

  <label for="link_body">Body:</label>
  <input
    type="text"
    name="link[body]"
    id="link_body"
    value="<%= @link.body %>">

  <h2>Post to Subs</h2>
  <% Sub.all.each do |sub| %>
    <label for="link_sub_ids_<%= sub.id %>"><%= sub.name %></label>
    <input
      type="checkbox"
      name="link[sub_ids][]"
      value="<%= sub.id %>"
      id="link_sub_ids_<%= sub.id %>"
      <% if @link.sub_ids.include?(sub.id) %>
        checked="checked"
      <% end %>
    />
  <% end %>

  <input type="submit">
</form>

app/views/links/edit.html.erb
<%= render :partial => "form" %>

app/views/links/new.html.erb
<%= render :partial => "form" %>

app/views/links/show.html.erb
  <h2>(<%= @link.votes %>) <%= link_to(@link.title,@link.url) %> [<%= link_to('up',upvote_link_url) %>|<%= link_to('down',downvote_link_url) %>]</h2>



<h2>Comments</h2>
<ul>
  <% comments_by_parent = @link.comments_by_parent%>
  <% comments_by_parent[nil].each do |top_level_comments| %>
    <li>
      <%= comment_partial(top_level_comments, comments_by_parent) %>
    </li>
  <% end %>
</ul>

app/views/subs/_form.html.erb
<% form_title = @sub.persisted? ? "Edit Sub" : "Create Sub" %>
<% submit_method = @sub.persisted? ? :put : :post %>
<% submit_url = @sub.persisted? ? sub_url(@sub) : subs_url %>

<h1><%= form_title %></h1>
<form action="<%= submit_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input
    type="hidden"
    name="_method"
    value="<%= submit_method %>">

  <label for="sub_name">Name</label>
  <input
    type="text"
    name="sub[name]"
    id="sub_name"
    value="<%= @sub.name %>">

  <% @sub.links.each_with_index do |link, i| %>
    <h2>Create Link</h2>
    <% link_id = "sub_links_attributes_#{i}" %>
    <% link_name = "sub[links_attributes][#{i}]" %>

    <label for="<%= link_id + "_url" %>">URL</label>
    <input
      type="hidden"
      name="<%= link_name %>[id]"
      value="<%= link.id %>">

    <input
      type="text"
      name="<%= link_name %>[url]"
      id="<%= link_id + "_url" %>"
      value="<%= link.url %>"><br>

      <label for="<%= link_id + "_title" %>">Title:</label>
      <input
        type="text"
        name="<%= link_name %>[title]"
        id="<%= link_id + "_url" %>"
        value="<%= link.title  %>"
      ><br>

      <label for="<%= link_id + "_body" %>">Body:</label>
      <input
        type="text"
        name="<%= link_name %>[body]"
        id="<%= link_id + "_url" %>"
        value="<%= link.body  %>"
      >
  <% end %>

  <input type="submit">
</form>

app/views/subs/edit.html.erb
<%= render :partial => "form" %>

app/views/subs/index.html.erb
<% @subs.each do |sub| %>
  <h3><%= link_to(sub.name,sub) %></h3>
<% end %>

app/views/subs/new.html.erb
<%= render :partial => "form" %>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>
<hr>
<% @sub.links.each do |link| %>
<h3><%= link.votes %> &mdash; <%= link_to(link.title,link.url) %></h3>
<%= link_to(link.body,link) %><hr>

<% end %>

app/views/users/new.html.erb
<h1>Create User</h1>

<form action="<%= users_url %>" method="post">
  <label for="user_username">Username</label>
  <input
    type="text"
    name="user[username]"
    value="<%= @user.username%>"
    id="user_username">
    
  <label for="user_password">Password</label>
  <input
    type="password"
    name="user[password]"
    value="<%= @user.password %>"
    id="user_password">
  
  <input type="submit">
</form>